ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS branch_name TEXT NULL;

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS address_line TEXT NULL;

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS district TEXT NULL;

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS city TEXT NULL;

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS postal_code TEXT NULL;

ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS country_code TEXT NULL DEFAULT 'SA';
